trigger: none
pool:
  name: 'Default'
variables:
  GITHUB_PAT: $(GITHUB_PAT)
  TEST_SIMPLE: "basic_test_value"
steps:
- checkout: none
- task: PowerShell@2
  displayName: 'Debug All Variables'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "=== ALL ENVIRONMENT VARIABLES ==="
      Get-ChildItem env: | Sort-Object Name | ForEach-Object {
          if ($_.Name -like "*PAT*" -or $_.Name -like "*TOKEN*" -or $_.Name -like "*SECRET*") {
              Write-Host "$($_.Name) = [REDACTED]"
          } else {
              Write-Host "$($_.Name) = $($_.Value)"
          }
      }
      
      Write-Host "`n=== SPECIFIC CHECKS ==="
      Write-Host "GITHUB_PAT exists: $([bool]$env:GITHUB_PAT)"
      Write-Host "TEST_SIMPLE: '$env:TEST_SIMPLE'"
      
      if ($env:TEST_SIMPLE -ne "basic_test_value") {
          Write-Error "Even basic variables aren't working"
      } else {
          Write-Host "Basic variables work, checking PAT..."
          if ([string]::IsNullOrEmpty($env:GITHUB_PAT)) {
              Write-Error "PAT variable is empty"
          } else {
              Write-Host "PAT variable has content (length: $($env:GITHUB_PAT.Length))"
          }
      }