# azure-trigger-test.yml
trigger: none  # Manual only
pool:
  name: 'Default'  # Your self-hosted agent
variables:
  GITHUB_REPO: "https://github.com/teppoaland/sbsaa.git"
  GITHUB_PAT: $(GITHUB_PAT)
steps:
- checkout: self  # Let Azure do normal checkout
  clean: true
- task: PowerShell@2
  displayName: 'Trigger GH Actions with [test] commit'
  inputs:
    targetType: 'inline'
    script: |
      $tempDir = "$env:AGENT_TEMPDIRECTORY/gh-trigger"
      if (Test-Path $tempDir) { Remove-Item $tempDir -Recurse -Force }
      git clone https://$($env:GITHUB_PAT)@github.com/teppoaland/sbsaa.git $tempDir
      cd $tempDir
      git config user.name "azure-pipelines"
      git config user.email "azure-pipelines@microsoft.com"
      git commit --allow-empty -m "[test] Trigger automated tests from Azure"
      git push origin main
      if ($LASTEXITCODE -eq 0) {
        Write-Host "SUCCESS: Trigger commit pushed successfully"
      } else {
        Write-Error "FAILED: Could not push trigger commit"
        exit 1
      }