# azure-trigger-test.yml
trigger: none  # Manual only

pool:
  name: 'Default'  # Your self-hosted agent

variables:
  GITHUB_REPO: "https://github.com/teppoaland/sbsaa.git"
  GITHUB_PAT: $(GITHUB_PAT)  # Stored as a secret in Azure DevOps

steps:
- checkout: none  # Do not automatically fetch any repository

- task: PowerShell@2
  displayName: 'Push trigger commit to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      $tempDir = "$env:AGENT_TEMPDIRECTORY/gh-trigger"
      if (Test-Path $tempDir) { Remove-Item $tempDir -Recurse -Force }

      $token = $env:GITHUB_PAT
      git clone https://$token@github.com/teppoaland/sbsaa.git $tempDir

      cd $tempDir
      git config user.name "azure-pipelines"
      git config user.email "azure-pipelines@microsoft.com"

      git commit --allow-empty -m "[test] Trigger automated tests from Azure"
      git push origin main

      if ($LASTEXITCODE -eq 0) {
        Write-Host "SUCCESS: Trigger commit pushed to GitHub"
        Write-Host "GitHub Actions will handle the rest independently"
      } else {
        Write-Error "FAILED: Could not push trigger commit"
        exit 1
      }
