# azure-trigger-gh.yml
trigger: none  # Manual only

pool:
  name: 'Default'  # self-hosted runner

variables:
  GIT_REPO: "https://github.com/teppoaland/sbsaa-tests.git"
  GIT_USER: "azure-bot"
  GIT_EMAIL: "azure-bot@company.com"

steps:
- task: PowerShell@2
  displayName: 'Trigger GH Actions via empty commit'
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.name "$(GIT_USER)"
      git config --global user.email "$(GIT_EMAIL)"
      
      if (-Not (Test-Path "repo")) { git clone $(GIT_REPO) repo }
      cd repo
      echo "# trigger test $(Get-Date)" >> trigger.log
      git add trigger.log
      git commit -m "[test] Triggered from Azure"
      git push origin main
