trigger: none
pool:
  name: 'Default'
steps:
- checkout: none
- task: PowerShell@2
  displayName: 'Push trigger commit to GitHub'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
  inputs:
    targetType: 'inline'
    script: |
      $token = $env:GITHUB_PAT
      
      if ([string]::IsNullOrEmpty($token)) {
          Write-Error "GitHub PAT token is missing"
          exit 1
      }
      
      Write-Host "Token found, proceeding with git operations"
      
      $tempDir = "$env:AGENT_TEMPDIRECTORY/gh-trigger"
      if (Test-Path $tempDir) { Remove-Item $tempDir -Recurse -Force }
      
      git clone "https://github-actions:$token@github.com/teppoaland/sbsaa.git" $tempDir
      cd $tempDir
      git config user.name "azure-pipelines"
      git config user.email "azure-pipelines@microsoft.com"
      git commit --allow-empty -m "[test] Trigger from Azure"
      git push origin main
      
      if ($LASTEXITCODE -eq 0) {
          Write-Host "SUCCESS: GitHub Actions triggered"
      } else {
          Write-Error "Push failed"
          exit 1
      }